apiVersion: v1
kind: Service
metadata:
  name: jkelcey-prac5p-service
spec:
  selector:
    app: prac5p-calculator-app
    tier: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3040
