apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkelcey-prac5p
  labels:
    app: prac5p-calculator-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prac5p-calculator-app
      tier: frontend
  template:
    metadata:
      labels:
        app: prac5p-calculator-app
        tier: frontend
    spec:
      containers:
      - name: calculator-app-docker
        image: jkelcey/sit323-737-2023-t1-prac5p:latest
        ports:
        - containerPort: 3040